import type { Recipe } from "../types/recipe";
import { syncRecipeToCloud, deleteRecipeFromCloud, syncBatchToCloud } from "./sync";
import { create, insertMultiple, search } from "@orama/orama";

let oramaDb: any = null;

const DB_NAME = "mypantry";
// Bumped to 2: wipes the old `recipes` store so stale embeddings from
// all-MiniLM-L6-v2 (384-dim, different checkpoint) don't pollute search.
// New model: Snowflake/snowflake-arctic-embed-s int4 (384-dim, ~61MB).
const DB_VERSION = 2;
const STORE_NAME = "recipes";

/**
 * Opens (and initialises on first run) the IndexedDB database.
 * The `recipes` object store uses `id` (a URL-derived slug) as its keyPath.
 */
function openDb(): Promise<IDBDatabase> {
    return new Promise((resolve, reject) => {
        const request = indexedDB.open(DB_NAME, DB_VERSION);

        request.onupgradeneeded = (event) => {
            const db = (event.target as IDBOpenDBRequest).result;
            // Delete the existing store on any version upgrade so that embeddings
            // generated by the previous model are not used in similarity search.
            if (db.objectStoreNames.contains(STORE_NAME)) {
                db.deleteObjectStore(STORE_NAME);
            }
            // Recreate with `id` as the primary key
            db.createObjectStore(STORE_NAME, { keyPath: "id" });
        };

        request.onsuccess = () => resolve(request.result);
        request.onerror = () => reject(request.error);
    });
}

/**
 * Persists a recipe object (with embedding) to IndexedDB.
 * Uses `put` so re-extracting the same URL simply updates the existing record.
 */
/**
 * Persists a recipe object (with embedding) to IndexedDB
 * and updates the saved URLs cache in chrome.storage.local.
 */
export async function saveRecipeLocally(recipe: Recipe): Promise<void> {
    if (recipe.tags) {
        recipe.tags = recipe.tags.map(t => t.toUpperCase());
    }
    const db = await openDb();
    await new Promise<void>((resolve, reject) => {
        const tx = db.transaction(STORE_NAME, "readwrite");
        const store = tx.objectStore(STORE_NAME);
        const request = store.put(recipe);
        request.onsuccess = () => resolve();
        request.onerror = () => reject(request.error);
        tx.oncomplete = () => db.close();
    });

    if (typeof chrome !== "undefined" && chrome.storage && chrome.storage.local && recipe.url) {
        try {
            const data: Record<string, any> = await chrome.storage.local.get("savedUrls");
            const urls: string[] = Array.isArray(data.savedUrls) ? data.savedUrls : [];
            if (!urls.includes(recipe.url)) {
                urls.push(recipe.url);
                await chrome.storage.local.set({ savedUrls: urls });
            }
        } catch (e) {
            console.warn("Failed to update savedUrls cache", e);
        }
    }

    oramaDb = null; // Invalidate cache

    // Fire-and-forget cloud sync — a failure here must never surface to the user.
    console.log(`[DB] Initiating cloud sync for recipe '${recipe.id}'...`);
    syncRecipeToCloud(recipe).catch((e) => console.warn("[Sync] Unexpected cloud save error:", e));
}

/**
 * Persists a batch of recipe objects to IndexedDB
 * and fires off a batch sync to the cloud.
 */
export async function importRecipesLocally(recipes: Recipe[]): Promise<void> {
    if (!recipes || recipes.length === 0) return;
    recipes.forEach(r => {
        if (r.tags) {
            r.tags = r.tags.map(t => t.toUpperCase());
        }
    });

    const db = await openDb();
    await new Promise<void>((resolve, reject) => {
        const tx = db.transaction(STORE_NAME, "readwrite");
        const store = tx.objectStore(STORE_NAME);

        // Use put to gracefully overwrite duplicates if any exist
        recipes.forEach(recipe => store.put(recipe));

        tx.oncomplete = () => {
            resolve();
            db.close();
        };
        tx.onerror = () => {
            reject(tx.error);
        };
    });

    if (typeof chrome !== "undefined" && chrome.storage && chrome.storage.local) {
        try {
            const data: Record<string, any> = await chrome.storage.local.get("savedUrls");
            const urls: Set<string> = new Set(Array.isArray(data.savedUrls) ? data.savedUrls : []);

            recipes.forEach(r => {
                if (r.url) urls.add(r.url);
            });

            await chrome.storage.local.set({ savedUrls: Array.from(urls) });
        } catch (e) {
            console.warn("Failed to update savedUrls cache during batch import", e);
        }
    }

    oramaDb = null; // Invalidate cache

    // Fire-and-forget cloud batch sync
    console.log(`[DB] Initiating batch cloud sync for ${recipes.length} imported recipes...`);
    syncBatchToCloud(recipes).catch((e) => console.warn("[Sync] Unexpected cloud batch save error:", e));
}

/**
 * Retrieves a single recipe by its id from IndexedDB.
 */
export async function getRecipe(id: string): Promise<Recipe | undefined> {
    const db = await openDb();
    return new Promise((resolve, reject) => {
        const tx = db.transaction(STORE_NAME, "readonly");
        const store = tx.objectStore(STORE_NAME);
        const request = store.get(id);
        request.onsuccess = () => resolve(request.result as Recipe | undefined);
        request.onerror = () => reject(request.error);
        tx.oncomplete = () => db.close();
    });
}

/**
 * Retrieves all recipes from IndexedDB.
 */
export async function getAllRecipes(): Promise<Recipe[]> {
    const db = await openDb();
    return new Promise((resolve, reject) => {
        const tx = db.transaction(STORE_NAME, "readonly");
        const store = tx.objectStore(STORE_NAME);
        const request = store.getAll();
        request.onsuccess = () => resolve(request.result as Recipe[]);
        request.onerror = () => reject(request.error);
        tx.oncomplete = () => db.close();
    });
}

/**
 * Deletes a recipe by its id.
 */
/**
 * Deletes a recipe by its id
 * and removes its URL from the chrome.storage.local cache.
 */
export async function deleteRecipe(id: string): Promise<void> {
    // Attempt to get the recipe first so we know its URL
    const recipe = await getRecipe(id);

    const db = await openDb();
    await new Promise<void>((resolve, reject) => {
        const tx = db.transaction(STORE_NAME, "readwrite");
        const store = tx.objectStore(STORE_NAME);
        const request = store.delete(id);
        request.onsuccess = () => resolve();
        request.onerror = () => reject(request.error);
        tx.oncomplete = () => db.close();
    });

    if (recipe && recipe.url && typeof chrome !== "undefined" && chrome.storage && chrome.storage.local) {
        try {
            const data: Record<string, any> = await chrome.storage.local.get("savedUrls");
            let urls: string[] = Array.isArray(data.savedUrls) ? data.savedUrls : [];
            urls = urls.filter(u => u !== recipe.url);
            await chrome.storage.local.set({ savedUrls: urls });
        } catch (e) {
            console.warn("Failed to clear savedUrls cache", e);
        }
    }

    oramaDb = null; // Invalidate cache

    // Fire-and-forget cloud delete — failures are logged, never thrown.
    deleteRecipeFromCloud(id).catch((e) => console.warn("[Sync] Unexpected cloud delete error:", e));
}

/**
 * Performs an in-memory vector search across all recipes using Orama.
 * Returns the top-k results sorted by relevance to the query embedding.
 */
export async function searchRecipes(
    queryEmbedding: number[],
    topK = 20,
    minScore = 0.4 // Lowered threshold to be more permissive (0.65 was too strict)
): Promise<Recipe[]> {
    const all = await getAllRecipes();

    if (!oramaDb) {
        oramaDb = await create({
            schema: {
                id: "string",
                embedding: "vector[384]",
            },
        });

        const docs = all
            .filter((r) => r.embedding && r.embedding.length === 384)
            .map((r) => ({
                id: r.id,
                embedding: r.embedding,
            }));

        if (docs.length > 0) {
            await insertMultiple(oramaDb, docs);
        }
    }

    if (!oramaDb) return [];

    const results = await search(oramaDb, {
        mode: "vector",
        vector: {
            value: queryEmbedding,
            property: "embedding",
        },
        similarity: minScore,
        limit: topK,
    });

    const recipeMap = new Map<string, Recipe>();
    for (const r of all) {
        recipeMap.set(r.id, r);
    }

    return results.hits
        .map((h) => recipeMap.get(h.id as string))
        .filter((r): r is Recipe => r !== undefined);
}
